print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
pertip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
tip = '{:.2f}'.format((bill / 100 * pertip + bill) / people, 2)
print(f"Each person should pay: ${tip}")